# Generated by Django 3.1 on 2020-08-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submit',
        ),
    ]
